services:
  fluent-bit-test:
    image: fluent/fluent-bit:3.2.0
    container_name: fluent-bit-cn
    ports:
      - "${FLUENTBIT_EXTERNAL_PORT}:24224"
    volumes:
      - ./docker/fluent-bit:/fluent-bit/etc
      - ./log:/var/log

  elasticsearch-test:
    image: bitnami/elasticsearch:8.11.4
    container_name: elasticsearch-cn
    ports:
      - "${ELASTIC_EXTERNAL_PORT}:9200"
    environment:
      - "discovery.type=single-node"

  kibana-test:
    image: bitnami/kibana:8.11.4
    container_name: kibana-cn
    links:
      - "elasticsearch-test"
    ports:
      - "${KIBANA_EXTERNAL_PORT}:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch-test:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch-test:9200

#  PHP
  php-fpm:
    image: php:8.4-fpm-alpine
    container_name: php-fpm
    hostname: php-fpm
    volumes:
      - ./public:/var/www/app/public
    #      - ./php-fpm.conf:/usr/local/etc/php-fpm.conf
    depends_on:
      - fluent-bit-test
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: asdf

  nginx:
    image: nginx:1.27.1-alpine
    depends_on:
      - php-fpm
    volumes:
      - ./public:/var/www/app/public
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
